patterns:

  budget-card:
    width: 300
    padding: 2em
    description: |
      The budget card is to be used to edit or see information about the exising budget.

  button-card:
    width: 400
    padding: 2em
    description: |
      The button cards are to be used for actions. They contain a button which asks to take action. The cards themselves should never be a link.

  icon-card:
    width: 400
    padding: 2em
    description: |
      The icon cards are used for highlights on the inside pages. For example, they should contain the general information of the budget. They should not be a link themselves, however elements on the card may contain links.

  icon-button-card:
    width: 400
    padding: 2em
    description: |
      The button icon cards are used to alert the users that they are about to make a permanent action. These cards are also accompanied by a button to confirm the action.

  sign-up-card:
    width: 400
    padding: 2em
    description: |
      This card is to be used on the landing page for new users.

description: |
  The cards provide a way for us to highlight important pieces of information and separate them from the body copy content.
