patterns:

  budget-card:
    width: 400
    padding: 2em
    description: |
      insert text.

  button-card:
    width: 400
    padding: 2em
    description: |
      The button cards are to be used for actions. They contain a button which asks to take action. The cards themselves should never be a link.

  icon-card:
    width: 400
    padding: 2em
    description: |
      The cards are used for highlights on the inside pages. For example, they should contain the general information of the budget. They should not be a link themselves, however elements on the card may contain links.

description: |
  The cards provide a way for us to highlight important pieces of information and separate them from the body copy content.
